name: Vuego CLI automation

jobs:
  default:
    desc: "Format, lint and test"
    steps:
      - task: fmt
      - task: lint
      - task: test

  fmt:
    desc: "Run formatters"
    steps:
      - goimports -w -local $(go list .) .
      - goimports-reviser -set-alias -format -imports-order "std,blanked,general,company,project" ./...
      - go fmt ./...
      - go mod tidy

  test:
    desc: "Run tests"
    passthru: true
    steps:
      - gotestsum ./... -- -count 1

  lint:
    desc: "Run linters"
    passthru: true
    steps:
      - go-fsck lint ./...
