name: Vuego CLI automation

vars:
  name: vuego-cli
  build:
    path: .
    goarch: [arm64, amd64]

jobs:
  default:
    desc: "Format, lint and test"
    steps:
      - task: fmt
      - task: lint
      - task: test
      - task: install

  fmt:
    desc: "Run formatters"
    steps:
      - goimports -w -local $(go list .) .
      - goimports-reviser -set-alias -format -imports-order "std,blanked,general,company,project" ./...
      - go fmt ./...
      - go mod tidy

  test:
    desc: "Run tests"
    passthru: true
    steps:
      - gotestsum ./... -- -count 1

  lint:
    desc: "Run linters"
    passthru: true
    steps:
      - go-fsck lint ./...
      - go vet ./...

  build:
    desc: "Build"
    depends_on: fmt
    vars:
      goos: linux
    steps:
      - for: goarch in ${{build.goarch}}
        env:
          vars:
            CGO_ENABLED: 0
            GOOS: ${{ goos }}
            GOARCH: ${{ goarch }}
        run: go build -ldflags="-X 'main.Version=${GIT_TAG}' -X 'main.Commit=${GIT_COMMIT}' -X 'main.CommitTime=${GIT_TIME}' -X 'main.Branch=${GIT_BRANCH}' -X 'main.Modified=${GIT_MODIFIED}'" -o bin/${{name}}-${GOOS}-${GOARCH} ${{build.path}}

  install:
    desc: "Install"
    depends_on: build
    steps:
      - cp -f ./bin/${{name}}-linux-$(dpkg --print-architecture) /usr/local/bin/${{name}}.new
      - mv -f /usr/local/bin/${{name}} /usr/local/bin/${{name}}.old
      - mv -f /usr/local/bin/${{name}}.new /usr/local/bin/${{name}}

  release:
    desc: "Release vuego"
    steps:
      - task: install
      - ./ci/release.yml build
      - ./ci/release.yml test

  publish:
    desc: "Publish release"
    depends_on: release
    steps:
      - ./ci/release.yml publish
